### PR TITLE
Fill the holes in the proof of the relaying–broadcasting equivalence theorem

### LINKED ISSUE #55: Fill the holes in the proof of the relaying–broadcasting equivalence theorem
Currently we don’t have simplifier support for bisimilarity reasoning yet, because #10 hasn’t been resolved yet. Therefore the proof of the relaying–broadcasting equivalence theorem contains fake proofs (`sorry`) for numerous steps. Our goal is to replace these fake proofs by proper proofs, building on the solution to #10.

### PR DESCRIPTION
**Pull request by javierdiaz72**
This resolves #55.

### CODE REVIEW

**Comment by jeltsch** [comment]
Could you please also merge the latest `master` commits into this branch? In particular, I’m interested in having 86c90ce in the branch, so that the build process doesn’t regenerate data under the session name `Utilities` (I’ve deleted all such data on my computer and would like my `~/.isabelle` directory to stay clean 😉).

**Comment by javierdiaz72** [comment]
> Could you please also merge the latest `master` commits into this branch? In particular, I’m interested in having [86c90ce](https://github.com/input-output-hk/fm-ouroboros/commit/86c90ce9e6e4061313ca6636f4021b5efec8f6a7) in the branch, so that the build process doesn’t regenerate data under the session name `Utilities` (I’ve deleted all such data on my computer and would like my `~/.isabelle` directory to stay clean ).

Done.

**Comment by jeltsch** [comment]
Could you also please adapt the code to use the features brought by #158?

**Comment by jeltsch** [comment]
I discovered that we actually don’t need the inner forward/backward bridge redundancy lemmas. Our use of them apparently stems from a time when we didn’t have `inner_bidirectional_bridge_redundancy` yet. Now we have it, and the code is more high-level when using it (no unfolding of bidirectional bridges).

I think we should retire the inner forward/backward redundancy lemmas, as they aren’t needed anymore and they are rather specialized. What do you think, @javierdiaz72?

**Comment by javierdiaz72** [comment]
> I discovered that we actually don’t need the inner forward/backward bridge redundancy lemmas. Our use of them apparently stems from a time when we didn’t have `inner_bidirectional_bridge_redundancy` yet. Now we have it, and the code is more high-level when using it (no unfolding of bidirectional bridges).
> 
> I think we should retire the inner forward/backward redundancy lemmas, as they aren’t needed anymore and they are rather specialized. What do you think, @javierdiaz72?

I agree that they are rather specialized, so we should retire them.

**Comment by jeltsch** [comment]
> > I think we should retire the inner forward/backward redundancy lemmas, as they aren’t needed anymore and they are rather specialized. What do you think, @javierdiaz72?
> 
> I agree that they are rather specialized, so we should retire them.

I’ve filed an issue for that (#163). Could you please work on that as well? Thanks. 🙂

**Comment by javierdiaz72** [comment]
> Could you also please adapt the code to use the features brought by #158?

Done.

**Comment by jeltsch** [comment]
Hi, @javierdiaz72! I’ve performed an overhaul of the `Relaying_Broadcasting_Equivalence` theory. Could you please look carefully through the new version, checking whether there are any problems with it? Thanks a lot.

**Comment by javierdiaz72** [comment]
> Hi, @javierdiaz72! I’ve performed an overhaul of the `Relaying_Broadcasting_Equivalence` theory. Could you please look carefully through the new version, checking whether there are any problems with it? Thanks a lot.

Beautiful! Approved. ;)

**Pull request merged**
