### PR TITLE
Add simplifier support for equivalence reasoning

### LINKED ISSUE #10: Add simplifier support for equivalence reasoning
Currently, when reasoning with bisimilarities, we need to apply core bisimilarities manually. This leads to long and hard-to-create proofs. Especially the need for manual application of compatibility (preservation) laws and associativity of parallel composition constitutes a hardship.

Our goal is to employ Isabelle’s simplifier to automate the creation of such boring proof steps. A challenge is that the simplifier seems to work only for *equational* reasoning by default. We want to make it work also for *equivalence* reasoning and thus in particular for *bisimilarity* reasoning.

  - [x] Research how to best use the simplifier for reasoning with arbitrary equivalences
  - [x] Implement simplifier support for equivalence reasoning

### PR DESCRIPTION
**Pull request by jeltsch**
This resolves #10.

### CODE REVIEW

**Comment by jeltsch** [comment]
I just discovered that the current implementation has a problem. Consider the following example code:
```
axiomatization example :: "[nat, nat] ⇒ bool" (infix "∼" 50) where
  example_is_equivalence [equivalence]:
    "equivp (∼)"
and
  example_successor_compatibility [equivalence_cong]:
    "n ∼ m ⟹ Suc n ∼ Suc m"

lemma "n ∼ Suc n ⟹ Suc n ∼ Suc (Suc n)"
  by equivalence_simp
```
The invocation of `equivalence_simp` at the end will hang. Apparently, the rules `equivalence_cong [simplified equivalence [THEN equivalence_rewrite_rule]]` aren’t proper congruence rules for the simplifier. A solution might be to switch to a proof method that involves classical reasoning (like `auto`) and use the above-mentioned rules as introduction rules.

**Comment by jeltsch** [comment]
The trick of using `auto` and then `intro` instead of `cong` works for the lemma in the previous comment but not for the following one:
```
lemma complex: ⟦n ∼ Suc (a + b); a + b ∼ a * b; Suc (a * b) ∼ m⟧ ⟹ Suc n ∼ Suc m
  sorry
```
Interestingly, this new lemma `complex` _can_ be solved with the current implementation of the proof method, the one that uses `simp` with `cong`.

**Comment by jeltsch** [comment]
After further thinking, I guess I finally got to the bottom of this issue.

I think the implementation of the proof method is just fine, and it’s actually the example in https://github.com/input-output-hk/fm-ouroboros/pull/83#issuecomment-507861286 that is bad. The lemma in this comment, which causes the hang, introduces `n ∼ Suc n` as an additional simplification rule. However, that’s a bad simplification rule, since already a rewriting system consisting solely of that rule is non-terminating. The hang has apparently nothing to do with congruence rules; it can already be caused by the following lemma:
```
lemma "⟦n ∼ Suc n; Suc n ∼ m⟧ ⟹ n ∼ m"
  by equivalence_simp
```

I think, we should leave the implementation as it is. Are you fine with that, @javierdiaz72?

**Comment by javierdiaz72** [comment]
Sure, I'm fine with that!

**Pull request merged**
